services:
  itflow:
    container_name: itflow
    environment:
      - TZ=${TZ}
      - ITFLOW_NAME=${ITFLOW_NAME}
      - ITFLOW_URL=${ITFLOW_URL}
      - ITFLOW_PORT=${ITFLOW_PORT_8080}
      - ITFLOW_REPO=github.com/itflow-org/itflow
      - ITFLOW-REPO_BRANCH=master
      - ITFLOW_LOG_LEVEL=info
      - ITFLOW_DB_HOST=itflow-db
      - ITFLOW_DB_PASS=${ITFLOW_DB_PASS}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: ${ITFLOW_RESTART}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/itflow/html:/var/www/html
    networks:
      - itflow-db

  itflow-db:
    container_name: itflow-db
    image: mariadb:10
    restart: always
    networks:
      - itflow-db
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MARIADB_DATABASE=itflow
      - MARIADB_USER=itflow
      - MARIADB_PASSWORD=${ITFLOW_DB_PASS}
    volumes:
      - ${DOCKERCONFDIR}/itflow/db:/var/lib/mysql/
    
volumes:
  itflow-db:

networks:
  itflow-db:
    name: itflow-db
    external: false
